added portal theme support
Metatavu/metaform-api-spec pull request #44
Opened 2022-06-16 12:33 UTC by Chi-Chu319

resolves #43

2022-06-16 12:34 UTC, Chi-Chu319 commented on swagger.yaml
> +          description: A list of portal files
```suggestion
          description: A list of portal themes
```

2022-06-16 12:35 UTC, Chi-Chu319 commented on swagger.yaml
> +          description: an updated export theme file
```suggestion
          description: an updated portal theme
```

2022-06-16 12:36 UTC, Chi-Chu319 commented on swagger.yaml
> +          description: Attempted to make a call to an non existant metaform
```suggestion
          description: Attempted to make a call to an non existant theme
```

2022-06-16 12:36 UTC, Chi-Chu319 commented on swagger.yaml
> +          description: Attempted to make a call to an non existant metaform
```suggestion
          description: Attempted to make a call to an non existant theme
```

2022-06-16 12:36 UTC, Chi-Chu319 commented on swagger.yaml
> +          description: Attempted to make a call to an non existant metaform
```suggestion
          description: Attempted to make a call to an non existant theme
```

2022-06-16 12:37 UTC, Chi-Chu319 commented on swagger.yaml
> +          description: Attempted to make a call to an non existant metaform
```suggestion
          description: Attempted to make a call to an non existant theme
```

2022-06-17 06:39 UTC, Chi-Chu319 commented on swagger.yaml
> +                $ref: "#/components/schemas/ExportThemeFile"
```suggestion
      responses:
        "200":
          description: an updated admin theme
          content:
            application/json;charset=utf-8:
              schema:
                $ref: "#/components/schemas/AdminTheme"
```

2022-06-17 06:39 UTC, Chi-Chu319 commented on swagger.yaml
> +          description: Created export admin theme
```suggestion
          description: Created admin theme
```

2022-06-17 10:00 UTC, anttileppa requested changes

2022-06-17 10:00 UTC, anttileppa commented on swagger.yaml
> +        name:
name and slug should be required

2022-06-17 10:03 UTC, anttileppa approved these changes

2022-07-13 07:19 UTC, Chi-Chu319 commented on swagger.yaml
> +          type: string
The data should be object

2022-07-18 06:16 UTC, Chi-Chu319 commented on swagger.yaml
> +        - slug
```suggestion
```

2022-07-21 08:33 UTC, merged